# Wedit Makefile for project zxscredit-09
SRCDIR=c:\zxscredit-09
CFLAGS=-IC:\lcc\include  -g2 
CC=$(LCCROOT)\bin\lcc.exe
LINKER=$(LCCROOT)\bin\lcclnk.exe
OBJS=\
	actions.obj \
	cancel.obj \
	cell.obj \
	curattr.obj \
	draw.obj \
	efects.obj \
	events.obj \
	file.obj \
	flash.obj \
	graphic.obj \
	help.obj \
	icons.obj \
	info.obj \
	main.obj \
	mouse.obj \
	moving.obj \
	newfile.obj \
	ok.obj \
	save.obj \
	sdl_win32_main.obj \
	stop.obj \
	tape.obj \
	warn.obj \
	write.obj

LIBS=sdl.lib
EXE=zxscredit.exe

$(EXE):	$(OBJS) Makefile
	$(LINKER)  -subsystem windows -o $(SRCDIR)\lcc\zxscredit.exe $(OBJS) $(LIBS)

# Build actions.c
ACTIONS_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

actions.obj: $(ACTIONS_C) $(SRCDIR)\actions.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\actions.c

# Build cancel.c
CANCEL_C=\

cancel.obj: $(CANCEL_C) $(SRCDIR)\cancel.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\cancel.c

# Build cell.c
CELL_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

cell.obj: $(CELL_C) $(SRCDIR)\cell.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\cell.c

# Build curattr.c
CURATTR_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

curattr.obj: $(CURATTR_C) $(SRCDIR)\curattr.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\curattr.c

# Build draw.c
DRAW_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

draw.obj: $(DRAW_C) $(SRCDIR)\draw.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\draw.c

# Build efects.c
EFECTS_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

efects.obj: $(EFECTS_C) $(SRCDIR)\efects.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\efects.c

# Build events.c
EVENTS_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

events.obj: $(EVENTS_C) $(SRCDIR)\events.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\events.c

# Build file.c
FILE_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

file.obj: $(FILE_C) $(SRCDIR)\file.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\file.c

# Build flash.c
FLASH_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

flash.obj: $(FLASH_C) $(SRCDIR)\flash.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\flash.c

# Build graphic.c
GRAPHIC_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

graphic.obj: $(GRAPHIC_C) $(SRCDIR)\graphic.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\graphic.c

# Build help.c
HELP_C=\

help.obj: $(HELP_C) $(SRCDIR)\help.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\help.c

# Build icons.c
ICONS_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

icons.obj: $(ICONS_C) $(SRCDIR)\icons.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\icons.c

# Build info.c
INFO_C=\

info.obj: $(INFO_C) $(SRCDIR)\info.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\info.c

# Build main.c
MAIN_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

main.obj: $(MAIN_C) $(SRCDIR)\main.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\main.c

# Build mouse.c
MOUSE_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

mouse.obj: $(MOUSE_C) $(SRCDIR)\mouse.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\mouse.c

# Build moving.c
MOVING_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

moving.obj: $(MOVING_C) $(SRCDIR)\moving.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\moving.c

# Build newfile.c
NEWFILE_C=\

newfile.obj: $(NEWFILE_C) $(SRCDIR)\newfile.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\newfile.c

# Build ok.c
OK_C=\

ok.obj: $(OK_C) $(SRCDIR)\ok.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\ok.c

# Build save.c
SAVE_C=\

save.obj: $(SAVE_C) $(SRCDIR)\save.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\save.c

# Build sdl_win32_main.c
SDL_WIN32_MAIN_C=\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\string.h\
	C:\lcc\include\ctype.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\windows.h\
	C:\lcc\include\win.h\
	C:\lcc\include\limits.h\
	C:\lcc\include\stdarg.h\
	C:\lcc\include\basetsd.h\
	C:\lcc\include\malloc.h\
	C:\lcc\include\direct.h\
	C:\lcc\include\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_main.h\

sdl_win32_main.obj: $(SDL_WIN32_MAIN_C) $(SRCDIR)\sdl_win32_main.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\sdl_win32_main.c

# Build stop.c
STOP_C=\

stop.obj: $(STOP_C) $(SRCDIR)\stop.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\stop.c

# Build tape.c
TAPE_C=\

tape.obj: $(TAPE_C) $(SRCDIR)\tape.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\tape.c

# Build warn.c
WARN_C=\

warn.obj: $(WARN_C) $(SRCDIR)\warn.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\warn.c

# Build write.c
WRITE_C=\
	$(SRCDIR)\main.h\
	C:\lcc\include\SDL\SDL.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_getenv.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\getopt.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_timer.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_audio.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_error.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_cdrom.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_events.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_active.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_keyboard.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_keysym.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_mouse.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\SDL_mutex.h\
	C:\lcc\include\SDL_main.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_rwops.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_joystick.h\
	C:\lcc\include\SDL_quit.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\SDL_video.h\
	C:\lcc\include\SDL_byteorder.h\
	C:\lcc\include\SDL_version.h\
	C:\lcc\include\SDL_types.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\begin_code.h\
	C:\lcc\include\close_code.h\
	C:\lcc\include\stdio.h\
	C:\lcc\include\string.h\
	C:\lcc\include\unistd.h\
	C:\lcc\include\io.h\
	C:\lcc\include\sys\stat.h\
	C:\lcc\include\stdlib.h\
	C:\lcc\include\stddef.h\
	C:\lcc\include\_syslist.h\
	C:\lcc\include\time.h\

write.obj: $(WRITE_C) $(SRCDIR)\write.c
	$(CC) -c $(CFLAGS) $(SRCDIR)\write.c

link:
	$(LINKER)  -subsystem windows -o $(SRCDIR)\lcc\zxscredit.exe $(OBJS) $(LIBS)

clean:
	del $(OBJS) c:\zxscredit-09\lcc\zxscredit.exe
